version: "3.9"
services:
  # 現在のディレクトリ内にある Dockerfile から構築したイメージを使用する
  web:
    build: .
    # ホストのポート 8000 にコンテナのポート 5000 を結びつける
    ports:
      - "8001:5000"
    # ホストのコードをコンテナの /code にマウントする[bind mountであることに注意]
    # volumes:
    #   - .:/code
    # 開発環境であることを示す環境変数を設定する
    # environment:
    #   FLASK_ENV: development
    #  Docker Hub レジストリにある公開 Redis イメージを使用する
  redis:
    image: "redis:alpine"