services: 
  db:
    image: mysql:5.7 
    volumes: 
      - db_data:/var/lib/mysql 
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: your_database
      MYSQL_USER: user_name
      MYSQL_PASSWORD: user_password

  web:
    build: ./rails_project 
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes: 
      - .:/myapp
    ports: 
      - "3000:3000"
    depends_on: 
      - db
      
volumes: 
    db_data:
